In [28]:
a = [12, 3.4, 34, 'cloudxlab', [2.3, 1.4]]
print(a[3])

cloudxlab


In [30]:
print(34 in a)

True


In [31]:
a = [1,2,3]    
c = a * 3

In [32]:
print(c)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [33]:
print(sum(c))

18


In [36]:
list = [12,23,43,[2,4,5], 2, 4,5]
list.pop(3)

[2, 4, 5]

In [37]:
list = ['cloudx', 'lab', 'provides', 'cloud', 'lab']
del list[1]
print(list)

['cloudx', 'provides', 'cloud', 'lab']


In [38]:
list = ['cloudx', 'lab', 'provides', 'cloud', 'lab']
list.remove('lab')

In [39]:
print(list)

['cloudx', 'provides', 'cloud', 'lab']


In [40]:
list = ['cloudx', 'lab', 'provides', 'cloud', 'lab']
del list[:]

In [41]:
print(list)

[]


In [1]:
with open("/cxldata/python_sample_file") as f:
    s = ""
    for line in f:
        print(line)
        s = s + line
    print(s)

This is a sample file for testing

for Python course for

learners in CloudxLab.

This is a sample file for testing
for Python course for
learners in CloudxLab.



In [22]:
def file_read_func(path):
    wcount = 0
    try:
        with open(path) as f:
            for line in f:
                sen = line.replace("\n"," ")
                words = sen.split(" ")
                for w in words:
                    wcount += len(w)
    except:
        wcount = -1
    return wcount

file_read_func("/cxldata/python_sample_file")
file_read_func("/cxldata/abc")

-1

In [27]:
check = 0
with open("/cxldata/python_sample_file") as f:
    for line in f:
        if(line.startswith('w')):
            check = check + 1
print (check)            

0


In [1]:
!ls

Bikes_problem.ipynb		End_to_end_project.ipynb  scala_spark.ipynb
Bikes_solution.ipynb		Practice1.ipynb		  test1.ipynb
cat_vs_noncat_classifier.ipynb	Practice2.ipynb		  Untitled1.ipynb
classify_clothes.ipynb		Python.ipynb		  Untitled.ipynb


In [7]:
def ordernum(a,b):
    if (a>b):
        return [a,b]
    else:
        return [b,a]

print (ordernum(5,4))    
print (ordernum(15,6))    
print (ordernum(1,16)) 

[5, 4]
[15, 6]
[16, 1]


In [6]:
def sq(x): return x*x
sq(10)

25

In [8]:
def mymap(a,f):
    r = []
    for i in a:
        v= f(i)
        r.append(v)
    return r

mymap([1,2,3,4], sq)

[1, 4, 9, 16]

In [13]:
def cube(x): return x*x*x
print (mymap([1,2,3,4], cube))
print (mymap([1,2,3,4,5], cube))

[1, 8, 27, 64]
[1, 8, 27, 64, 125]


In [14]:
print (mymap([1,2,3,4,5], print))

1
2
3
4
5
[None, None, None, None, None]


In [16]:
mymap([1,2,3,4,5], lambda x:x*2)

[2, 4, 6, 8, 10]

In [17]:
sum = lambda x,y: x+y
sum(4,7)

11

In [18]:
mymap([2,3,4,5], lambda x: x* int(input("Multiplier: ")))

Multiplier: 2
Multiplier: 3
Multiplier: 4
Multiplier: 5


[4, 9, 16, 25]

In [ ]:
x = ["apple", "banana", "eggs"]
x[1] = "Banana1"
print (x)
x.append("cereals")
print(x)
x.sort()
print(x)
x.reverse()
print(x)
dir(x)
x.pop()

In [2]:
ddd= dict()
ddd['age']=12
ddd['course']=183
print(ddd)

{'age': 12, 'course': 183}


In [11]:
ddd['chuck'] = 500
print(ddd)
x =ddd.get('age')
print (x)

{'age': 12, 'course': 183, 'chuck': 500}
12


In [12]:
print(ddd.keys())
for i in ddd : print (i)

dict_keys(['age', 'course', 'chuck'])
age
course
chuck


In [12]:
# Tuple

(x, y) = (12, "Hello")
print (x)
print (y)

12
Hello


In [16]:
(0, 2, 2000000) < (0, 3, 4)

True

In [17]:
def dict_func(string):
    l = string.split(" ")
    d = dict()
    for word in l:
        if(d.get(word)):
            d[word] += 1
        else:
            d[word] = 1
    return d
dict_func('the quick brown fox jumps over the lazy dog')

{'the': 2,
 'quick': 1,
 'brown': 1,
 'fox': 1,
 'jumps': 1,
 'over': 1,
 'lazy': 1,
 'dog': 1}

In [21]:
t = (12,323, 'd', [1,23], False)

In [24]:
t = (1,)
type(t)

tuple

In [26]:
t=tuple()
print(t)

()


In [1]:
t1 = tuple("1,2,3,4,5")
t2 = tuple([1,2,3,4,5])
t3 = tuple((1,2,3,4,5))
print(t1)
print(t2)
print(t3)
print(len(t1))
print(len(t2))
print(len(t3))

('1', ',', '2', ',', '3', ',', '4', ',', '5')
(1, 2, 3, 4, 5)
(1, 2, 3, 4, 5)
9
5
5


Network Programming

In [3]:
## using Urllib in python

from urllib import *
fhand = request.urlopen('http://www.py4inf.com/code/romeo.txt')

for line in fhand:
    print(line.strip())

b'But soft what light through yonder window breaks'
b'It is the east and Juliet is the sun'
b'Arise fair sun and kill the envious moon'
b'Who is already sick and pale with grief'


In [4]:
from urllib import *
fhand = request.urlopen('http://www.py4inf.com/code/romeo.txt')

count = dict()
for line in fhand:
    words = line.split()
    

In [7]:
# Beautiful Soup
## web scrape


from urllib import *
from bs4 import BeautifulSoup

url = input("url - ")

html = request.urlopen(url).read()
soup = BeautifulSoup(html)

tags = soup('a')
for tag in tags:
    print(tag.get('href', None))


url - https://cloudxlab.com
https://cloudxlab.com
/events/past-events/
/

/c/eict-iit-roorkee-courses/
/#specialization_courses
/lab/

/bootml/

/jobs/
/contact-us?mid=pj
https://discuss.cloudxlab.com

/course/all/?type=free
//cloudxlab.com/blog/

/contact-us
/bootml/
/accounts/login/
/accounts/signup/
tel:1-412-568-3901

mailto:reachus@cloudxlab.com
/course/84/certificate-course-artificial-intelligence-deep-learning-iit-roorkee/
/#all_courses
/c/eict-iit-roorkee-courses/
#specialization_courses
/lab
https://www.aninews.in/news/national/general-news/covid-19-iit-roorkee-launches-online-course-to-upskill-students-professionals20200420133820/
/course/84/certificate-course-artificial-intelligence-deep-learning-iit-roorkee/
/course/73/data-science-specialization-eict-iitr
/course/73/data-science-specialization-eict-iitr
/course/71/machine-learning-specialization-eict-iitr
/course/71/machine-learning-specialization-eict-iitr
/course/67/big-data-engineering-with-hadoop-and-spark
/course/67/b

In [12]:
# Python Objects

class PartyAnimal:
    x =0 
    
    def party(self):
        self.x = self.x +1
        print("So far: ", self.x)

an = PartyAnimal()
an.party()
an.party()
an.party()

b= PartyAnimal()
b.party()

print (type(b))

So far:  1
So far:  2
So far:  3
So far:  1
<class '__main__.PartyAnimal'>


In [21]:
## Constructor
## __init__(self)

class PartyAnimal:
    x =0 
    
    def __init__(self):
        print('I m constructor')
    
    def party(self):
        self.x = self.x +1
        print("So far: ", self.x)
        
    def __del__(self):
        print('I m distructor', self.x)

In [22]:
a = PartyAnimal()
a.party()

I m constructor
I m distructor 1
So far:  1


In [27]:
class PartyAnimal:
    x =0 
    name = ''
    def __init__(self, nam):
        self.name = nam
        print(self.name, 'constructed!!')
    
    def party(self):
        self.x = self.x +1
        print(self.name, " party count: ", self.x)
        
class footbalFan(PartyAnimal):
    points = 1    
    def touchdown(self):
        self.points = self.points + 7
        self.party()
        print(self.name, ' points: ', self.points)
        

In [28]:
a = PartyAnimal('Ria')
a.party()

b = footbalFan('Armin')
b.party()
b.touchdown()

Ria constructed!!
Ria  party count:  1
Armin constructed!!
Armin  party count:  1
Armin  party count:  2
Armin  points:  8


In [29]:
for x in (a,b):
    print(x.party())

Ria  party count:  2
None
Armin  party count:  3
None


In [32]:
import sys
%timeit sys.path

62.5 ns ± 4.43 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [35]:
f = lambda x: x*x

In [36]:
f(4)

16

In [37]:
foo = [1,2,3,6,7,9,12,13,15]

In [40]:
div_of_three = filter(lambda x: x%3==0, foo)
print(list(div_of_three))

[3, 6, 9, 12, 15]


In [1]:
[i*i for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [5]:
import itertools
import functools

In [7]:
list(map(lambda x:x*x, range(10)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [2]:
import numpy as np

In [4]:
# Numpy np

a = np.array([10,20,30,40,50])
b = np.arange(5)
c = a + b
print(a)
print(b)
print(c)

[10 20 30 40 50]
[0 1 2 3 4]
[10 21 32 43 54]


In [13]:
def number_of_lines():
    fhand = open('/cxldata/datasets/project/mbox-short.txt')
    inp = fhand.read()
    lines= 0
    for c in inp:
        if c=='\n':
            lines +=1
    fhand.close()
    return lines
    
count = number_of_lines()
print (count)

1910


In [18]:
def count_number_of_lines():
    
    fhand = open('/cxldata/datasets/project/mbox-short.txt')
    count = 0
    for line in fhand:
        line = line.rstrip() # Remove new line characters from right
        if line.startswith('Subject:'):
            print(line)
            count +=1
    return count

c = count_number_of_lines()
print(c)
            

27


In [28]:
def average_spam_confidence():
    
    fhand = open('/cxldata/datasets/project/mbox-short.txt')
    count = 0
    value = 0
    for line in fhand:
        line = line.rstrip() # Remove new line characters from right
        if line.startswith('X-DSPAM-Confidence:'):
            l = line.split('X-DSPAM-Confidence:')
            value += float(l[1])
            #print(value)
            count +=1
            
    return value/count

c = average_spam_confidence()
print(c)
         

0.7507185185185187


In [41]:
def find_email_sent_days():
    days_count = {}
    
    fhand = open('/cxldata/datasets/project/mbox-short.txt')
    count = 0
    value = 0
    for line in fhand:
        line = line.rstrip() # Remove new line characters from right
        if line.startswith('From '):
            #print(line)
            s = line.split()
            day = s[2]
            if day in days_count:
                days_count[day] +=1
            else:
                days_count[day] =1
    return days_count

c = find_email_sent_days()
print(c)

{'Sat': 1, 'Fri': 20, 'Thu': 6}


In [46]:
def count_message_from_email():
    count_email = {}
    
    fhand = open('/cxldata/datasets/project/mbox-short.txt')
    count = 0
    value = 0
    for line in fhand:
        line = line.rstrip() # Remove new line characters from right
        if line.startswith('From '):
            #print(line)
            s = line.split()
            email = s[1]
            if email in count_email:
                count_email[email] +=1
            else:
                count_email[email] =1
    return count_email

c = count_message_from_email()
print(c)

{'stephen.marquard@uct.ac.za': 2, 'louis@media.berkeley.edu': 3, 'zqian@umich.edu': 4, 'rjlowe@iupui.edu': 2, 'cwen@iupui.edu': 5, 'gsilver@umich.edu': 3, 'wagnermr@iupui.edu': 1, 'antranig@caret.cam.ac.uk': 1, 'gopal.ramasammycook@gmail.com': 1, 'david.horwitz@uct.ac.za': 4, 'ray@media.berkeley.edu': 1}


In [55]:
def count_message_from_domain():
    count_email = {}
    
    fhand = open('/cxldata/datasets/project/mbox-short.txt')
    count = 0
    value = 0
    for line in fhand:
        line = line.rstrip() # Remove new line characters from right
        if line.startswith('From '):
            #print(line)
            s = line.split()
            email = s[1].split('@')[1]
            if email in count_email:
                count_email[email] +=1
            else:
                count_email[email] =1
    return count_email

c = count_message_from_domain()
print(c)

{'uct.ac.za': 6, 'media.berkeley.edu': 4, 'umich.edu': 7, 'iupui.edu': 8, 'caret.cam.ac.uk': 1, 'gmail.com': 1}
